### ISSUE TITLE
pivot not set to one specified in config file

### ISSUE THREAD

**Issue by gotenxds** [WeAthFoLD/MetaSprite#7]
Hi, when generating the atlas each frame seems to have some random number for the x and y values of the pivot, I tried setting bottom center and custom (0.5, 0) but I still get different numbers for each frame.

![image](https://user-images.githubusercontent.com/3519520/47626144-52df1700-db32-11e8-83c9-6f4ddf02e0ce.png)

![image](https://user-images.githubusercontent.com/3519520/47626135-45299180-db32-11e8-913b-25df25d424ae.png)

**Comment by WeAthFoLD** [comment]
The number is correct. Because each frame has different regions where the pixels are actually drawn, the crop regions are different, resulting different calculated pivots.

If you play back the animation in a gameobject, you will find that behaviour is correct.

BTW you can uncheck 'Dense Pack' in import settings to make each sprite occupy full region.
